name: Validate JSONs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: addressbook.schema.json
          INPUT_JSONS: mainnet/addressbook.json,testnet/addressbook.json,devnet/addressbook.json
